- platform: GitHub
  username: j-freddy
  icon: fa-brands fa-github
  link: "https://github.com/j-freddy"
- platform: LinkedIn
  username: Freddy Jiang
  icon: fa-brands fa-linkedin
  link: "https://www.linkedin.com/in/jiangfreddy/"
- platform: Instagram
  username: jiang.freddy
  icon: fa-brands fa-instagram
  link: "https://www.instagram.com/jiang.freddy/"
- platform: Discord
  username: RDg0#9896
  icon: fa-brands fa-discord
  link: "https://discordapp.com/users/362278194851872770"
- platform: LiChess
  username: afMirrorUR
  icon: fa-solid fa-chess-king
  link: "https://lichess.org/@/afMirrorUR"
